### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST localhost:8080/api/v1/convert
Content-Type: application/json
Accept: application/json

{
  "category": "TEMPERATURE",
  "fromUnit": "Celsius",
  "toUnit": "Fahrenheit",
  "value": 35
}

###
POST localhost:8080/api/v1/convert
Content-Type: application/json
Accept: application/json

{
  "category": "TIME",
  "fromUnit": "minute",
  "toUnit": "hour",
  "value": 180
}
###

POST localhost:8080/api/v1/convert
Content-Type: application/json
Accept: application/json

{
  "category": "WEIGHT",
  "fromUnit": "kilogram",
  "toUnit": "gram",
  "value": 10
}

###
GET localhost:8080/api/v1/categories
###
GET localhost:8080/api/v1/sample-payload
###
GET localhost:8080/api/v1/check-health